### ISSUE TITLE
Spack Error: LockTimeoutError

### ISSUE THREAD

**Issue by emilannevelink** [ArjunaCluster/ArjunaUsers#73]
If you notice an issue on arjuna, please first search the existing issues and ensure that it has not been reported. If you notice a similar example, please comment on that issue.

> Please update the issue's title with something informative

Please provide the following information to help us help you:

## Basic Info
Your Name: Emil Annevelink
Your Andrew ID: eannevel

## Where it happened
Job Ids: N/A
Node(s) on which the problem occurred: head node

## What Happened
Expected Behavior: spack install cudnn
Observed Behavior:
spack looks for cuda, doesn't like using cuda@11.4.0, so wants to install a new cuda@11.3.1, but that fails with `Error: Failed to install cuda due to LockTimeoutError: Timed out waiting for a write lock.`

## Log Files
Location of Log file Showing the Error:
Location of Script showing [Minimum Working Example]:

Please also attach any logs and the submission script to this issue.

```log # 'log' here because it's a log file
Submit log files like this (Notice the ``` before and after this block)
this ensures logs are formated correctly (Ie. Comments don't become headings)

```

```bash # 'bash' here it's a bash script
#!/bin/bash
#SBATCH --ntasks 28
#SBATCH --cpus-per-task 1
...

```

[Minimum Working Example]: https://en.wikipedia.org/wiki/Minimal_working_example

## What I've Tried

Please List what you've tried to debug the issue. Please include commands and resulting output

1) I googled the error issue and read through https://github.com/spack/spack/issues/9166 but couldn't understand
2) I tried going to an older version of cuda@10.2.89 but that just gave me the error when installing cudnn.

```shell # 'shell' here because we're showing a shell command
> awesome_command
Output from awesome_command
```

> If you do not have any of the above, please explain why you do not have it, and submit the issue, however, the more information you give us, the better we can help you.

**Comment by abillscmu** [comment]
I cannot reproduce this. Try `spack --debug install...` to give us a little more

**Comment by emilannevelink** [comment]
Here is the output

```
spack --debug install cudnn
==> [2021-09-29-15:09:58.294711] Imported install from built-in commands
==> [2021-09-29-15:09:58.298494] Reading config file /home/spack/spack/etc/spack/defaults/config.yaml
==> [2021-09-29-15:09:58.339325] Reading config file /etc/spack/config.yaml
==> [2021-09-29-15:09:58.344062] Imported install from built-in commands
==> [2021-09-29-15:09:58.348451] Reading config file /home/spack/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-29-15:09:58.366467] Reading config file /etc/spack/upstreams.yaml
==> [2021-09-29-15:09:58.370809] Reading config file /home/spack/spack/etc/spack/defaults/config.yaml
==> [2021-09-29-15:09:58.405915] Reading config file /etc/spack/config.yaml
==> [2021-09-29-15:09:58.410077] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-29-15:09:58.410173] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-29-15:09:58.427926] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-29-15:09:58.428025] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-29-15:09:58.428642] Reading config file /home/spack/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-29-15:09:58.443288] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-29-15:09:58.443391] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-29-15:09:58.459685] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-29-15:09:58.459784] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-29-15:09:58.459916] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2021-09-29-15:09:58.460505] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/spack/spack/etc/spack/defaults
==> [2021-09-29-15:09:58.460595] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/spack/spack/etc/spack/defaults/linux
==> [2021-09-29-15:09:58.460707] [BOOTSTRAP CONFIG SCOPE] name=system, path=/etc/spack
==> [2021-09-29-15:09:58.460791] [BOOTSTRAP CONFIG SCOPE] name=system/linux, path=/etc/spack/linux
==> [2021-09-29-15:09:58.460869] [BOOTSTRAP CONFIG SCOPE] name=site, path=/home/spack/spack/etc/spack
==> [2021-09-29-15:09:58.460953] [BOOTSTRAP CONFIG SCOPE] name=site/linux, path=/home/spack/spack/etc/spack/linux
==> [2021-09-29-15:09:58.461024] [BOOTSTRAP CONFIG SCOPE] name=user, path=/home/eannevel/.spack
==> [2021-09-29-15:09:58.461087] [BOOTSTRAP CONFIG SCOPE] name=user/linux, path=/home/eannevel/.spack/linux
==> [2021-09-29-15:09:58.467464] [BOOTSTRAP ROOT SPEC] clingo: clingo-bootstrap@spack+python %gcc target=x86_64
==> [2021-09-29-15:09:58.467565] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2021-09-29-15:09:58.467940] Reading config file /home/spack/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-29-15:09:59.017014] Reading config file /home/spack/spack/etc/spack/defaults/config.yaml
==> [2021-09-29-15:09:59.042256] Reading config file /etc/spack/config.yaml
==> [2021-09-29-15:09:59.161163] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6 /vcipwnf57slgoo7busvvkzjkk7vydeb5" provides the "clingo" Python module
==> [2021-09-29-15:09:59.161574] Reading config file /home/spack/spack/etc/spack/defaults/repos.yaml
==> [2021-09-29-15:09:59.164978] Reading config file /etc/spack/repos.yaml
==> [2021-09-29-15:09:59.238188] Reading config file /home/spack/spack/etc/spack/defaults/config.yaml
==> [2021-09-29-15:09:59.263963] Reading config file /etc/spack/config.yaml
==> [2021-09-29-15:09:59.395208] Reading config file /etc/spack/compilers.yaml
==> [2021-09-29-15:09:59.409395] Reading config file /home/eannevel/.spack/linux/compilers.yaml
==> [2021-09-29-15:09:59.416190] Reading config file /home/spack/spack/etc/spack/defaults/packages.yaml
==> [2021-09-29-15:09:59.455849] Reading config file /etc/spack/packages.yaml
==> [2021-09-29-15:10:00.333572] opt_criterion(16, deprecated versions used)
==> [2021-09-29-15:10:00.333900] opt_criterion(15, version weight)
==> [2021-09-29-15:10:00.334023] opt_criterion(14, number of non-default variants (roots))
==> [2021-09-29-15:10:00.334133] opt_criterion(13, multi-valued variants)
==> [2021-09-29-15:10:00.334236] opt_criterion(12, preferred providers for roots)
==> [2021-09-29-15:10:00.334335] opt_criterion(11, number of non-default variants (non-roots))
==> [2021-09-29-15:10:00.334450] opt_criterion(9, preferred providers (non-roots))
==> [2021-09-29-15:10:00.334548] opt_criterion(8, compiler mismatches)
==> [2021-09-29-15:10:00.334645] opt_criterion(7, version badness)
==> [2021-09-29-15:10:00.334741] opt_criterion(6, count of non-root multi-valued variants)
==> [2021-09-29-15:10:00.334838] opt_criterion(5, non-preferred compilers)
==> [2021-09-29-15:10:00.334934] opt_criterion(4, target mismatches)
==> [2021-09-29-15:10:00.335030] opt_criterion(3, non-preferred targets)
==> [2021-09-29-15:10:00.417971] Initializing the build queue from the build requests
==> [2021-09-29-15:10:00.418118] Initializing the build queue for cudnn
==> [2021-09-29-15:10:00.419079] Processing dependencies for cudnn-8.2.0.53-11.3-mi65wgdvgbjgecumuz4r23jya7x6jzm7: ('build', 'link', 'run')
==> [2021-09-29-15:10:00.419590] Pkg id libiconv-1.16-c3paxlisrnye43eaz2mik3qq7cijxrx4 has the following dependents:
==> [2021-09-29-15:10:00.419694] - libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk
==> [2021-09-29-15:10:00.445110] Pkg id pkgconf-1.8.0-zh2gwknvgdienjfugxphf5yllavz6wcr has the following dependents:
==> [2021-09-29-15:10:00.445220] - libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk
==> [2021-09-29-15:10:00.454924] Pkg id xz-5.2.5-3itohrarf3gb3fe5nej35zvn5h3wfw4l has the following dependents:
==> [2021-09-29-15:10:00.455031] - libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk
==> [2021-09-29-15:10:00.468306] Pkg id zlib-1.2.11-xzfuiy6a5csxs6l6rpezodmkv6hjtbm3 has the following dependents:
==> [2021-09-29-15:10:00.468423] - libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk
==> [2021-09-29-15:10:00.478319] Pkg id libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk has the following dependents:
==> [2021-09-29-15:10:00.478450] - cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b
==> [2021-09-29-15:10:00.494518] Pkg id cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b has the following dependents:
==> [2021-09-29-15:10:00.494628] - cudnn-8.2.0.53-11.3-mi65wgdvgbjgecumuz4r23jya7x6jzm7
==> [2021-09-29-15:10:00.515368] Removing failure marking for cuda
==> [2021-09-29-15:10:00.534601] Removing failure marking for cudnn
==> [2021-09-29-15:10:00.534834] Pkg id cudnn-8.2.0.53-11.3-mi65wgdvgbjgecumuz4r23jya7x6jzm7 has the following dependents:
==> [2021-09-29-15:10:00.536147] Ensure all dependencies know all dependents across specs
[+] /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/libiconv-1.16-c3paxlisrnye43eaz2mik3qq7cijxrx4
==> [2021-09-29-15:10:00.539307] Flagging libiconv-1.16-c3paxlisrnye43eaz2mik3qq7cijxrx4 as installed
==> [2021-09-29-15:10:00.539407] Removing libiconv-1.16-c3paxlisrnye43eaz2mik3qq7cijxrx4 from libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk's uninstalled dependencies.
==> [2021-09-29-15:10:00.539585] libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk: Removed libiconv-1.16-c3paxlisrnye43eaz2mik3qq7cijxrx4 from uninstalled deps list: {'pkgconf-1.8.0-zh2gwknvgdienjfugxphf5yllavz6wcr', 'xz-5.2.5-3itohrarf3gb3fe5nej35zvn5h3wfw4l', 'zlib-1.2.11-xzfuiy6a5csxs6l6rpezodmkv6hjtbm3'}
[+] /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/pkgconf-1.8.0-zh2gwknvgdienjfugxphf5yllavz6wcr
==> [2021-09-29-15:10:00.540164] Flagging pkgconf-1.8.0-zh2gwknvgdienjfugxphf5yllavz6wcr as installed
==> [2021-09-29-15:10:00.540249] Removing pkgconf-1.8.0-zh2gwknvgdienjfugxphf5yllavz6wcr from libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk's uninstalled dependencies.
==> [2021-09-29-15:10:00.540365] libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk: Removed pkgconf-1.8.0-zh2gwknvgdienjfugxphf5yllavz6wcr from uninstalled deps list: {'xz-5.2.5-3itohrarf3gb3fe5nej35zvn5h3wfw4l', 'zlib-1.2.11-xzfuiy6a5csxs6l6rpezodmkv6hjtbm3'}
[+] /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/xz-5.2.5-3itohrarf3gb3fe5nej35zvn5h3wfw4l
==> [2021-09-29-15:10:00.540945] Flagging xz-5.2.5-3itohrarf3gb3fe5nej35zvn5h3wfw4l as installed
==> [2021-09-29-15:10:00.541041] Removing xz-5.2.5-3itohrarf3gb3fe5nej35zvn5h3wfw4l from libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk's uninstalled dependencies.
==> [2021-09-29-15:10:00.541150] libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk: Removed xz-5.2.5-3itohrarf3gb3fe5nej35zvn5h3wfw4l from uninstalled deps list: {'zlib-1.2.11-xzfuiy6a5csxs6l6rpezodmkv6hjtbm3'}
[+] /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/zlib-1.2.11-xzfuiy6a5csxs6l6rpezodmkv6hjtbm3
==> [2021-09-29-15:10:00.541720] Flagging zlib-1.2.11-xzfuiy6a5csxs6l6rpezodmkv6hjtbm3 as installed
==> [2021-09-29-15:10:00.541806] Removing zlib-1.2.11-xzfuiy6a5csxs6l6rpezodmkv6hjtbm3 from libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk's uninstalled dependencies.
==> [2021-09-29-15:10:00.541910] libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk: Removed zlib-1.2.11-xzfuiy6a5csxs6l6rpezodmkv6hjtbm3 from uninstalled deps list: set()
[+] /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk
==> [2021-09-29-15:10:00.542498] Flagging libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk as installed
==> [2021-09-29-15:10:00.542585] Removing libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk from cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b's uninstalled dependencies.
==> [2021-09-29-15:10:00.542691] cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b: Removed libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk from uninstalled deps list: set()
==> [2021-09-29-15:10:00.543532] Acquiring a write lock on cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b with timeout 1e-09
==> [2021-09-29-15:10:00.548174] Creating stage lock spack-stage-cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b
==> [2021-09-29-15:10:00.548455] Installing cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b
==> [2021-09-29-15:10:00.548564] Searching for binary cache of cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b
==> [2021-09-29-15:10:00.548757] Reading config file /home/spack/spack/etc/spack/defaults/mirrors.yaml
==> [2021-09-29-15:10:00.552675] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-29-15:10:00.552780] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-29-15:10:00.961628] Did not find linux-centos7-broadwell-gcc-11.2.0-cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b.spec.yaml on https://mirror.spack.io/build_cache/linux-centos7-broadwell-gcc-11.2.0-cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b.spec.yaml
  Download failed: HTTP Error 404: Not Found
==> [2021-09-29-15:10:00.967800] No binary for cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b found: installing from source
==> [2021-09-29-15:10:01.060125] '/usr/bin/git' 'describe' '--tags' '--match' 'v*'
==> [2021-09-29-15:10:01.397730] [TOOLCHAIN] MATCH Gcc
==> [2021-09-29-15:10:01.402413] Adding compiler bin/ paths: /home/spack/spack/lib/spack/env /home/spack/spack/lib/spack/env/case-insensitive /home/spack/spack/lib/spack/env/gcc
==> [2021-09-29-15:10:01.461835] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2021-09-29-15:10:01.594339] '/home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/bin/g++' '-v' '/tmp/spack-implicit-link-infob1uosjra/main.c' '-o' '/tmp/spack-implicit-link-infob1uosjra/output'
==> [2021-09-29-15:10:01.701492] parsing implicit link info
==> [2021-09-29-15:10:01.702446] linker line:  /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/collect2 -plugin /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/liblto_plugin.so -plugin-opt=/home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/lto-wrapper -plugin-opt=-fresolution=/tmp/ccrheC2m.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -rpath /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib:/home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib64 --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /tmp/spack-implicit-link-infob1uosjra/output /lib/../lib64/crt1.o /lib/../lib64/crti.o /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0/crtbegin.o -L/home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0 -L/home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../.. /tmp/ccMwpMYR.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0/crtend.o /lib/../lib64/crtn.o
==> [2021-09-29-15:10:01.702667] linkdir: /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0
==> [2021-09-29-15:10:01.702772] linkdir: /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../lib64
==> [2021-09-29-15:10:01.702865] linkdir: /lib/../lib64
==> [2021-09-29-15:10:01.702949] linkdir: /usr/lib/../lib64
==> [2021-09-29-15:10:01.703030] linkdir: /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../..
==> [2021-09-29-15:10:01.703164] found raw link dirs: /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0, /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../..
==> [2021-09-29-15:10:01.703398] found link dirs: /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib/gcc/x86_64-pc-linux-gnu/11.2.0, /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib64, /lib64, /usr/lib64, /home/spack/.spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-11.2.0-badtwcass7lspftppao5xnb2a4n77nbo/lib
==> [2021-09-29-15:10:11.853457] Using cached archive: /home/eannevel/.spack/var/spack/cache/_source-cache/archive/ad/ad93ea98efced35855c58d3a0fc326377c60917cb3e8c017d3e6d88819bf2934
==> [2021-09-29-15:10:21.388030] Staging unexpanded archive /tmp/eannevel/spack-stage/spack-stage-cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/cuda_11.3.1_465.19.01_linux.run in /tmp/eannevel/spack-stage/spack-stage-cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/spack-src
==> [2021-09-29-15:10:21.388868] Created stage in /tmp/eannevel/spack-stage/spack-stage-cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b
==> [2021-09-29-15:10:21.389119] No patches needed for cuda
==> [2021-09-29-15:10:21.389244] cuda: Building cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b [Package]
==> [2021-09-29-15:10:21.401912] cuda: Executing phase: 'install'
==> [2021-09-29-15:12:20.562075] FileNotFoundError: [Errno 2] No such file or directory: '/home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/repos'
==> [2021-09-29-15:12:20.562609] Installing /tmp/eannevel/spack-stage/spack-stage-cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/spack-build-out.txt to /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/spack-build-out.txt
==> [2021-09-29-15:12:20.563682] Installing /tmp/eannevel/spack-stage/spack-stage-cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/spack-build-01-install-out.txt to /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/spack-build-01-install-out.txt
==> [2021-09-29-15:12:20.564421] Installing /tmp/eannevel/spack-stage/spack-stage-cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/spack-build-env.txt to /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/spack-build-env.txt
==> [2021-09-29-15:12:20.572837] Installing /home/spack/spack/var/spack/repos/builtin/packages/cuda/package.py to /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/repos/builtin/packages/cuda
==> [2021-09-29-15:12:20.576700] Installing /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/libxml2-2.9.12-nu7skt4wzq3z36wnmrvafn4oa2ww3bwk/.spack/repos/builtin/packages/libxml2 to /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/repos/builtin/packages/libxml2
==> [2021-09-29-15:12:20.581820] Installing /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/libiconv-1.16-c3paxlisrnye43eaz2mik3qq7cijxrx4/.spack/repos/builtin/packages/libiconv to /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/repos/builtin/packages/libiconv
==> [2021-09-29-15:12:20.585571] Installing /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/pkgconf-1.8.0-zh2gwknvgdienjfugxphf5yllavz6wcr/.spack/repos/builtin/packages/pkgconf to /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/repos/builtin/packages/pkgconf
==> [2021-09-29-15:12:20.589434] Installing /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/xz-5.2.5-3itohrarf3gb3fe5nej35zvn5h3wfw4l/.spack/repos/builtin/packages/xz to /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/repos/builtin/packages/xz
==> [2021-09-29-15:12:20.592895] Installing /home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/zlib-1.2.11-xzfuiy6a5csxs6l6rpezodmkv6hjtbm3/.spack/repos/builtin/packages/zlib to /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b/.spack/repos/builtin/packages/zlib
==> [2021-09-29-15:12:20.595414] Reading config file /home/spack/spack/etc/spack/defaults/modules.yaml
==> [2021-09-29-15:12:20.625508] Reading config file /home/spack/spack/etc/spack/defaults/linux/modules.yaml
==> [2021-09-29-15:12:20.632941] Reading config file /etc/spack/modules.yaml
==> [2021-09-29-15:12:20.667506] Warning: Module file already exists : skipping creation
file : /home/eannevel/.spack/share/spack/lmod/linux-centos7-x86_64/gcc/11.2.0/cuda/11.3.1-jhtkzt3.lua
spec : cuda@11.3.1%gcc@11.2.0~dev arch=linux-centos7-broadwell ^libiconv@1.16%gcc@11.2.0 libs=shared,static arch=linux-centos7-broadwell ^libxml2@2.9.12%gcc@11.2.0~python arch=linux-centos7-broadwell ^pkgconf@1.8.0%gcc@11.2.0 arch=linux-centos7-broadwell ^xz@5.2.5%gcc@11.2.0~pic libs=shared,static arch=linux-centos7-broadwell ^zlib@1.2.11%gcc@11.2.0+optimize+pic+shared arch=linux-centos7-broadwell
==> [2021-09-29-15:12:20.667730] NO MODULE WRITTEN: list of enabled module files is empty
==> [2021-09-29-15:12:21.425337] Writing manifest file: No manifest from binary
==> [2021-09-29-15:12:31.535049] cuda: Successfully installed cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b
  Fetch: 10.15s.  Build: 2m 8.74s.  Total: 2m 18.89s.
[+] /home/eannevel/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b
==> [2021-09-29-15:12:34.553619] Flagging cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b as failed: Timed out waiting for a write lock.
==> [2021-09-29-15:12:34.559989] Warning: Skipping build of cudnn-8.2.0.53-11.3-mi65wgdvgbjgecumuz4r23jya7x6jzm7 since cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b failed
==> [2021-09-29-15:12:34.560153] Flagging cudnn-8.2.0.53-11.3-mi65wgdvgbjgecumuz4r23jya7x6jzm7 as failed
==> [2021-09-29-15:12:34.564347] Error: Failed to install cuda due to LockTimeoutError: Timed out waiting for a write lock.
==> [2021-09-29-15:12:35.941515] Downgrading to a read lock on cuda-11.3.1-jhtkzt3rt2sscifbua3lmuddp7n2633b with timeout 1e-09
==> [2021-09-29-15:12:35.942357] Error: cudnn-8.2.0.53-11.3-mi65wgdvgbjgecumuz4r23jya7x6jzm7: Package was not installed
==> [2021-09-29-15:12:35.942573] InstallError: Installation request failed.  Refer to reported errors for failing package(s).
==> [2021-09-29-15:12:35.942644] Error: Installation request failed.  Refer to reported errors for failing package(s).
Traceback (most recent call last):
  File "/home/spack/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/spack/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/home/spack/spack/lib/spack/spack/cmd/install.py", line 470, in install
    install_specs(args, kwargs, zip(abstract_specs, specs))
  File "/home/spack/spack/lib/spack/spack/cmd/install.py", line 274, in install_specs
    builder.install()
  File "/home/spack/spack/lib/spack/spack/installer.py", line 1671, in install
    raise InstallError('Installation request failed.  Refer to '
spack.installer.InstallError: Installation request failed.  Refer to reported errors for failing package(s).
```

**Comment by emilannevelink** [comment]
So it looks like there is a problem with my spack instances and I couldn't install any package. we got around this using 
`spack -L install *`
